export enum COLORS {
  GRAY_COLOR = '#a49e9e',
  MAIN_BACKGROUND_COLOR = '#E2E2DF',
  WARNING_COLOR = '#DE763C',
  GREEN_COLOR = '#8DDE3C',
  MODAL_BACKGROUND_COLOR = 'rgba(0,0,0,0.7)',
  BLACK_COLOR = '#101010',
}
