// ROUTES

export enum MOVIES_STACK_ROUTES {
  MOVIES = 'MOVIES',
  MOVIE_DETAILS = 'MOVIE_DETAILS',
}

export enum SEARCH_STACK_ROUTES {
  SEARCH = 'SEARCH',
}

export enum MODAL_ROUTES {
  ERROR = 'ERROR',
}

// NAVIGATORS

export enum NAVIGATORS {
  MOVIES_NAVIGATOR = 'MOVIES_NAVIGATOR',
  BOTTOM_TAB_NAVIGATOR = 'BOTTOM_TAB_NAVIGATOR',
  SEARCH_NAVIGATOR = 'SEARCH_NAVIGATOR',
}

// TABS

export enum TABS_NAMES {
  HOME = 'Home',
  SEARCH = 'Search',
}
